version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: ./docker/prod/backend/Dockerfile
    container_name: backend
    depends_on:
      - postgresql
    volumes:
      - ./backend:/backend
    env_file:
      - ./.envs/prod/.django
      - ./.envs/prod/.postgres
    ports:
      - "8000:8000"
    command: /start

  postgresql:
    image: postgres:13-alpine3.14
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.envs/.postgres
  frontend:
    build:
      context: .
      dockerfile: ./docker/local/frontend/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend
    command: "npm run build "

  nginx:
    image: nginx:1.21.3
    volumes:
      - ./docker/prod/nginx/templates:/etc/nginx/templates
      - ./docker/prod/nginx/conf.d:/etc/nginx/conf.d
      - ./frontend/build:/var/www/frontend/build
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=bibliothecam.test
      - NGINX_PORT=80

volumes:
  postgres_data:
